#!/bin/bash

strip_expected() {
  awk '
BEGIN {
  s = 0
}

$0 == "/* EXPECTED" {
  s = 1
  next
}

$0 == "EXPECTED */" {
  s = 0
  next
}

s == 1 {
  next
}

{ print $0 }
' $1 > $1.tmp
  mv $1.tmp $1
}


script=$1
file=${script}.obl
rm -rf stdout stderr

strip_expected $file

obelix $script > stdout 2> stderr
code=$?

echo "/* EXPECTED" >> $file
echo "--exit-- $code" >> $file
if [ -s stdout ] ; then
    echo "--stdout--" >> $file
    cat stdout >> $file
    echo "--" >> $file
fi
if [ -s stderr ] ; then
    echo "--stderr--" >> $file
    cat stderr >> $file
    echo "--" >> $file
fi
echo "EXPECTED */" >> $file

if ! grep -q "^$script\$" tests ; then
    echo $script >> tests
fi

rm -rf stdout stderr
