#!/bin/bash

scripts=$(cat tests)
         
check_output() {
  expected=$(awk -v tag="--$1--" '
BEGIN {
  s = 0
}

$0 == tag {
  s = 1
  next
}

/^--$/ {
  s = 0
  next
}

s == 1 {
  print $0
}
' $2)
  result=$(cat $1)
  if [ "$result" != "$expected" ] ; then
    echo "${script}: Unexpected $1"
    cat $1
    exit 1
  fi
}

for script in $scripts ; do
  echo $script
  file=${script}.obl
  rm -rf stdout stderr

  expected_code=$(grep -- "--exit--" ${file} | awk '{print $2}')
  [ -z $expected_code ] && expected_code=0
  fail=""

  obelix $script > stdout 2> stderr
  code=$?
  if [ "$code" != "$expected_code" ] ; then
    echo "${script}: Exit code ${code} != ${expected_code}"
    exit 1
  fi
  check_output stdout $file
  check_output stderr $file
done

rm -rf stdout stderr
