# TODO: Handle debug/release libs.

IF(PCRE2_INSTALL_DIR )
  MESSAGE ( STATUS "Using override PCRE2_INSTALL_DIR ${PCRE2_INSTALL_DIR}} to find PCRE2" )
  SET ( PCRE2_INCLUDE_DIR  "${PCRE2_INSTALL_DIR}/include" )
  # SET ( PCRE2_LIBRARY_DIR  "${PCRE2_INSTALL_DIR}/lib" )
  FIND_LIBRARY( PCRE2_LIBRARY NAMES pcre2-8d PATHS "${PCRE2_INSTALL_DIR}/lib" )
  FIND_LIBRARY( PCRE2POSIX_LIBRARY NAMES pcre2posixd PATHS "${PCRE2_INSTALL_DIR}/lib" )
ELSE ( PCRE2_INSTALL_DIR )
  FIND_PATH( PCRE2_INCLUDE_DIR pcre2.h "C:\\Program Files (x86)\\PCRE2\\include")
  FIND_LIBRARY( PCRE2_LIBRARY pcre2-8d "C:\\Program Files (x86)\\PCRE2\\lib")
  FIND_LIBRARY( PCRE2POSIX_LIBRARY pcre2posixd "C:\\Program Files (x86)\\PCRE2\\lib")
ENDIF ( PCRE2_INSTALL_DIR )

IF ( PCRE2_INCLUDE_DIR AND PCRE2_LIBRARY AND PCRE2POSIX_LIBRARY )
  SET( PCRE2_FOUND 1 )
  SET ( PCRE2_LIBRARIES "${PCRE2_LIBRARY}" "${PCRE2POSIX_LIBRARY}" )
  SET(HAVE_PCRE2_H 1)
  MESSAGE ( STATUS "Found PCRE2: ${PCRE2_LIBRARIES}" )
ENDIF ( PCRE2_INCLUDE_DIR AND PCRE2_LIBRARY AND PCRE2POSIX_LIBRARY )

MARK_AS_ADVANCED(
  PCRE2_INCLUDE_DIR
  PCRE2_LIBRARIES
  PCRE2_LIBRARY
  PCRE2POSIX_LIBRARY )
